from supabase import create_client, Client

SUPABASE_URL = "https://bozklyppogqfnytpmfda.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvemtseXBwb2dxZm55dHBtZmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMzQwMjMsImV4cCI6MjA4NjcxMDAyM30.eKqTf58ERiSEyjknBLWK90NQ9q5BmwtMnWYqCkxl8ww"

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
